spring:
    cloud:
        stream:
            bindings:
                attributes_change:
                    content-type: application/json
                    destination: attributes.changement
                SYNC_CUSTOMER_ATTR_TO_CRM:
                    content-type: application/json
                    destination: attributes.changement
                    group: sync.customer.attr.to.crm.asst-queue
                ASSIGN_BY_UNION_ID:
                    content-type: application/json
                    destination: xuegutang.user.exchange
                    group: assign.by.union.id.asst-queue
                SYNC_XGT_USER_CREATED:
                    content-type: application/json
                    destination: xuegutang.user.exchange
                    group: sync.xgt.user.created.asst-queue
                SYNC_XGT_USER_UPDATED:
                    content-type: application/json
                    destination: xuegutang.user.exchange
                    group: sync.xgt.user.updated.asst-queue
                SYNC_XGT_USER_ATTR_CHANGED:
                    content-type: application/json
                    destination: attributes.changement
                    group: sync.xgt.user.attr.changed.asst-queue
                VISIT_COURSE_BEHAVIOR:
                    content-type: application/json
                    destination: xuegutang.course.events
                    group: visit.course.behavior.asst-queue
                BUY_COURSE_BEHAVIOR:
                    content-type: application/json
                    destination: xuegutang.order.exchange
                    group: buy.course.behavior.asst-queue
                OUTPUT_CUSTOMER_RELATION:
                    content-type: application/json
                    destination: attributes.changement
                    group: customer.relation.queue
                INPUT_CUSTOMER_RELATION:
                    content-type: application/json
                    destination: attributes.changement
                    group: customer.relation.queue
                SYNC_GROUP_ID_CHANGED_TO_CUSTOMER:
                    content-type: application/json
                    destination: attributes.changement
                    group:  sync.group.id.changed.to.customer.asst-queue
                INPUT_CUSTOMER_QUESTION_BEHAVIOR:
                    content-type: application/json
                    destination: xuegutang.question.events
                    group: xuegutang.question.events.qaQuestioned
                INPUT_CUSTOMER_LOGIN_BEHAVIOR:
                    content-type: application/json
                    destination: dx.guba.user.events
                    group: dx.guba.user.events.logined
                INPUT_CUSTOMER_INTERACT_BEHAVIOR:
                    content-type: application/json
                    destination: xgt.topic
                    group: xgt.livechat
                OUTPUT_CUSTOMER_FEED_PROCESSOR:
                    content-type: application/json
                    destination: asst.server.exchange
                CUSTOMER_RELATION_CHANGED_TO_CRM:
                    content-type: application/json
                    destination: attributes.changement
                    group: customer.relation.to.crm.asst-queue
                INPUT_CUSTOMER_ACTIVITY:
                    content-type: application/json
                    destination: xuegutang.user.activities
                    group: xgt.user.activities.queue
            rabbit:
                bindings:
                    SYNC_CUSTOMER_ATTR_TO_CRM:
                        consumer:
                            bindingRoutingKey: attributes.t_customer_attr
                    ASSIGN_BY_UNION_ID:
                        consumer:
                            bindingRoutingKey: user_credential_created
                    SYNC_XGT_USER_CREATED:
                        consumer:
                            bindingRoutingKey: user_created
                    SYNC_XGT_USER_UPDATED:
                        consumer:
                            bindingRoutingKey: user_updated
                    SYNC_XGT_USER_ATTR_CHANGED:
                        consumer:
                            bindingRoutingKey: attributes.user_attributes
                    VISIT_COURSE_BEHAVIOR:
                        consumer:
                            bindingRoutingKey: xuegutang.course.courseViewHistory
                    BUY_COURSE_BEHAVIOR:
                        consumer:
                            bindingRoutingKey: ORDER_PAID.*
                    SYNC_GROUP_ID_CHANGED_TO_CUSTOMER:
                        consumer:
                            bindingRoutingKey: attributes.t_user_attr
                    OUTPUT_CUSTOMER_RELATION:
                        producer:
                            routing-key-expression: headers.routingKey
                    INPUT_CUSTOMER_RELATION:
                        consumer:
                            bindingRoutingKey: customer.relation.changed
                    INPUT_CUSTOMER_QUESTION_BEHAVIOR:
                        consumer:
                            bindingRoutingKey: events.xuegutang.ASKED
                    INPUT_CUSTOMER_LOGIN_BEHAVIOR:
                        consumer:
                            bindingRoutingKey: events.USER_LOGINED
                    INPUT_CUSTOMER_INTERACT_BEHAVIOR:
                        consumer:
                            bindingRoutingKey: xgt.livechat
                    OUTPUT_CUSTOMER_FEED_PROCESSOR:
                        producer:
                            routing-key-expression: headers.routingKey
                    CUSTOMER_RELATION_CHANGED_TO_CRM:
                        consumer:
                            bindingRoutingKey: customer.relation.changed
                    INPUT_CUSTOMER_ACTIVITY:
                        consumer:
                            bindingRoutingKey: xuegutang.useractivities.*